"""Page 4: Remediations — view and manage pending/resolved remediations."""

import sys
from pathlib import Path
_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import json
import streamlit as st
import pandas as pd

st.set_page_config(page_title="Remediations | RAGOps", layout="wide")

from database.db_client import get_pending_remediations, update_remediation_status, get_connection
from dashboard.components.theme import inject_theme, render_glossary_sidebar

inject_theme()
render_glossary_sidebar()

st.title("Remediations")
st.caption("Automated remediation proposals generated by the analysis engine based on failure patterns.")

# ── Pending remediations ──────────────────────────────────────────────────────
st.subheader("Pending Remediations")
pending = get_pending_remediations()

if not pending:
    st.success("No pending remediations — system is healthy!")
else:
    for rem in pending:
        priority_color = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}.get(
            rem.get("priority", "low"), "⚪"
        )
        with st.expander(
            f"{priority_color} [{rem.get('priority', '—').upper()}] {rem.get('alert_type', '—')} — {rem.get('timestamp', '')[:10]}"
        ):
            c1, c2 = st.columns([3, 1])
            with c1:
                st.markdown(f"**Root Cause:** {rem.get('root_cause', '—')}")
                st.markdown(f"**Recommended Action:** {rem.get('remediation_text', '—')}")
                steps = rem.get("specific_steps")
                if steps:
                    if isinstance(steps, str):
                        try:
                            steps = json.loads(steps)
                        except Exception:
                            steps = [steps]
                    st.markdown("**Specific Steps:**")
                    for step in steps:
                        st.markdown(f"- {step}")
            with c2:
                st.metric("Confidence", f"{float(rem.get('confidence', 0)) * 100:.0f}%")
                if st.button("Mark Resolved", key=f"resolve_{rem['remediation_id']}"):
                    update_remediation_status(rem["remediation_id"], "resolved", "Manually marked resolved")
                    st.rerun()
                if st.button("Mark Won't Fix", key=f"skip_{rem['remediation_id']}"):
                    update_remediation_status(rem["remediation_id"], "dismissed", "Marked won't fix")
                    st.rerun()

st.divider()

# ── Remediation history ───────────────────────────────────────────────────────
st.subheader("Remediation History")
with get_connection() as conn:
    rows = conn.execute(
        """
        SELECT remediation_id, timestamp, alert_type, priority, status, confidence, outcome
        FROM remediations
        ORDER BY timestamp DESC
        LIMIT 50
        """
    ).fetchall()

if rows:
    df = pd.DataFrame([dict(r) for r in rows])
    df["remediation_id"] = df["remediation_id"].str[:8] + "…"
    df["timestamp"] = df["timestamp"].str[:19]
    df["confidence"] = df["confidence"].apply(lambda x: f"{float(x or 0) * 100:.0f}%")
    st.dataframe(df, use_container_width=True)
else:
    st.info("No remediations recorded yet. They are generated automatically after probe cycles detect failure patterns.")
